### ISSUE TITLE
ftp for clinvar true set has changed 

### ISSUE THREAD

**Issue by edgarjavi** [quinlan-lab/pathoscore#31]
There is a new version of the vcf in clinvar, the file with the 20170802 data is archived. Here is the new line of code from the make.sh file with the new location

wget ftp://ftp.ncbi.nih.gov/pub/clinvar/vcf_GRCh37/vcf_2.0/archive/2017/clinvar_${date}.vcf.gz

**Comment by jimhavrilla** [comment]
That's already in the make.sh

Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by jimhavrilla** [comment]
You mean the september one is new?
ftp://ftp.ncbi.nih.gov/pub/clinvar/vcf_GRCh37/vcf_2.0/clinvar_20170905.vcf.gz
?

Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by edgarjavi** [comment]
yeah the clinvar make.sh wont run because the ftp location is outdated

**Comment by jimhavrilla** [comment]
I will update the date then.

Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by jimhavrilla** [comment]
Or do you recommend we move to the archive location?

Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by edgarjavi** [comment]
Exactly, the line I sent above gets the file with the old date.

**Comment by jimhavrilla** [comment]
Actually I think I have a fix.  I can try to pull if the newest one is there and exists, otherwise, check the archive for the date.  This will probably need to be changed in 2018 as well, since the archives will shift there.  Probably a constantly mutable make.sh to stay up-to-date.  Thanks for making me aware of it.  I'll push a fix.

**Comment by brentp** [comment]
let's keep it so it points to the latest file in the archive directory.

**Comment by jimhavrilla** [comment]
done.
