### ISSUE TITLE
add clinical utility table for a list of provided genes

### ISSUE THREAD

**Issue by jimhavrilla** [quinlan-lab/pathoscore#38]
accuracy * number of variants scored for each gene

**Comment by jimhavrilla** [comment]
make table scrollable, sorted by score (optionally)
on the command line we want it to work something like:
python pathoscore.py evaluate --functional --prefix clinvar -s CCR -s CADD -s GERP -s MPC -s REVEL --suffix --goi list_of_genes pdf pathogenic.vcf.gz benign.vcf.gz
where goi is "genes of interest" and expects a file with a single-column list of genes for which to score clinical utility

**Comment by arq5x** [comment]
Nice work. The ability to sort the table by each tool's scores (asc, desc) and to scroll/paginate for long lists would be great. Lastly, I think you just need 3 digits of precision after the decimal once you dig into the potential issues with the way the score is calculated.

**Comment by jimhavrilla** [comment]
Doesn't seem like sorting by tool is a feature plot.ly is capable of adding.  I would probably have to use some other software to accomplish that.  Scrolling is inherent in plot.ly though.

**Comment by arq5x** [comment]
I assume you can bring in external JS libraries?  Perhaps: http://tristen.ca/tablesort/demo/

**Comment by jimhavrilla** [comment]
completed by #39
